### ISSUE TITLE
执行go generate没有生成数据

### ISSUE THREAD

**Issue by akinoccc** [wksw/17track-golang-sdk#2]
貌似 cmd 的 package 里面没有 `// go:generate` 指令

执行 ` go run github.com/wksw/17track-golang-sdk/cmd/17track` 是可以的

**Comment by wksw** [comment]
命令在models.go文件中， 17track这命令装成功了没？

**Comment by akinoccc** [comment]
> 命令在models.go文件中， 17track这命令装成功了没？

怎么验证是否装成功？直接执行17track吗

**Comment by wksw** [comment]
是的 go generate 最终执行的就是17track这个命令
https://github.com/wksw/17track-golang-sdk/blob/85d786ee0894b5d7ff05da8af259e57d45f273f4/models.go#L18

**Comment by akinoccc** [comment]
貌似没有安装成功
```shell
zsh: command not found: 17track
```

**Comment by wksw** [comment]
> 貌似没有安装成功
> ```shell
> zsh: command not found: 17track
> ```

有报什么错误吗？go get 那条命令

**Comment by akinoccc** [comment]
> > 貌似没有安装成功
> > ```shell
> > zsh: command not found: 17track
> > ```
> 
> 有报什么错误吗？go get 那条命令

没有任何报错🫠

![image](https://github.com/user-attachments/assets/8158a1c3-1817-4a11-829d-3ebd5ad0b9aa)

**Comment by wksw** [comment]
which 17track 有内容输出吗？

**Comment by akinoccc** [comment]
> which 17track 有内容输出吗？

提示`17track not found`

**Comment by wksw** [comment]
go install  github.com/wksw/17track-golang-sdk/cmd/17track

**Comment by akinoccc** [comment]
> go install github.com/wksw/17track-golang-sdk/cmd/17track

还是not found，也没有报错

**Comment by wksw** [comment]
你的的GOPATH变量有值吗？

**Comment by akinoccc** [comment]
> 你的的GOPATH变量有值吗？

有的

![image](https://github.com/user-attachments/assets/a3187e26-6975-4463-84f8-f902361370d8)

**Comment by wksw** [comment]
不行就源码拉下来手动build 一个呗 go build -o 17track ./cmd/17track

**Comment by akinoccc** [comment]
> 不行就源码拉下来手动build 一个呗 go build -o 17track ./cmd/17track

也行

**Comment by akinoccc** [comment]
解决了，看到 bin 目录是有对应的二进制文件的，是系统环境变量的问题，将 gopath 的 bin 路径添加到系统变量的 path 就行了

**Comment by wksw** [comment]
> 解决了，看到 bin 目录是有对应的二进制文件的，是系统环境变量的问题，将 gopath 的 bin 路径添加到系统变量的 path 就行了

好的， 如果你在用的过程中有啥问题的话可以更新下， 我也不确定这个库现在是否可用，太久没有使用了， 不知道17track那边的API接口是否变更过了

**Comment by akinoccc** [comment]
> > 解决了，看到 bin 目录是有对应的二进制文件的，是系统环境变量的问题，将 gopath 的 bin 路径添加到系统变量的 path 就行了
> 
> 好的， 如果你在用的过程中有啥问题的话可以更新下， 我也不确定这个库现在是否可用，太久没有使用了， 不知道17track那边的API接口是否变更过了

ok，我可以帮忙维护
